### ISSUE TITLE
Add OpenCensus Feature

### ISSUE THREAD

**Issue by kpango** [yahoojapan/garm#13]
At the present time, garm supports only standard output logging.
I think we have to support opencensus logging for Prometheus, Jaguar, Zipkin, Stack Driver, etc..

**Comment by kpango** [comment]
I think that there is no need to develop another sidecar.

I think you need to implement it directly in Garm using [opencensus-go](https://github.com/census-instrumentation/opencensus-go)

**Comment by WindzCUHK** [comment]
continue in: https://github.com/AthenZ/garm/issues/6
