### ISSUE TITLE
whitelist, blacklist r.Name matches even if wildcard not specified

### ISSUE THREAD

**Issue by akira-masuda** [yahoojapan/garm#57]
I want to ask whether it's a specification or not.

When you specify whitelist or blacklist in garm, regexp matches when r.Name is not specified with wildcard.
(not strictly matched)

### examples

if you specify whitelist below

```
Verb:      "dummyVerb",
Namespace: "dummyNamespace",
APIGroup:  "dummyAPIGroup",
Resource:  "dummyResource",
Name:      "dummyName",
```

it matches with 

- `dummyVerb-dummyNamespace-dummyAPIGroup-dummyResource-dummyName`
- `dummyVerb-dummyNamespace-dummyAPIGroup-dummyResource-dummyNamexxxx`
- `dummyVerb-dummyNamespace-dummyAPIGroup-dummyResource-dummyNameyyyy`

#### expected result

In above case, it is more intuitive if it only matches with `dummyVerb-dummyNamespace-dummyAPIGroup-dummyResource-dummyName`

### cause

MatchString matches if it contains the string
https://github.com/yahoojapan/garm/blob/367ec9efa67bf25ec31fc3db967e6be827f2c555/config/config.go#L279

This happens in r.Verb (suffix match)  r.Name (prefix match)

- you can try here: https://play.golang.org/p/gQR-nghc4QF

**Comment by falz-tino** [comment]
Thank you for your issue and sorry for the inconvenience.  This is not the expected specification.
We expected each entry of the whitelist and blacklist should have a wildcard character (`*` or `?`) if wildcard match is needed, but not true.

We will fix this unexpected specification, but we are sorry to take some time.

**Comment by akira-masuda** [comment]
@falz-tino Thanks, got it. I'll close this issue, please let me know if there is any update.
